CREATE SCHEMA source_layer;

CREATE TABLE source_layer.New_Monthly_HC_Report (
    [id] numeric(18,0) NULL,
    [gci id] varchar(50) NULL,
    [first name] varchar(50) NULL,
    [last name] varchar(50) NULL,
    [job title] varchar(50) NULL,
    [hr_business_type] varchar(50) NULL,
    [client code] varchar(50) NULL,
    [start date] datetime NULL,
    [termdate] datetime NULL,
    [Final_End_date] datetime NULL,
    [NBR] money NULL,
    [Merged Name] varchar(100) NULL,
    [Super Merged Name] varchar(100) NULL,
    [market] varchar(50) NULL,
    [defined_New_VAS] varchar(8) NULL,
    [IS_SOW] varchar(7) NOT NULL,
    [GP] money NULL,
    [NextValue] datetime NULL,
    [termination_reason] varchar(100) NULL,
    [FirstDay] datetime NULL,
    [Emp_Status] varchar(25) NULL,
    [employee_category] varchar(50) NULL,
    [LastDay] datetime NULL,
    [ee_wf_reason] varchar(50) NULL,
    [old_Begin] numeric(2,1) NULL,
    [Begin HC] numeric(38,36) NULL,
    [Starts - New Project] numeric(38,36) NULL,
    [Starts- Internal movements] numeric(38,36) NULL,
    [Terms] numeric(38,36) NULL,
    [Other project Ends] numeric(38,36) NULL,
    [OffBoard] numeric(38,36) NULL,
    [End HC] numeric(38,36) NULL,
    [Vol_term] numeric(38,36) NULL,
    [adj] numeric(38,36) NULL,
    [YYMM] int NULL,
    [tower1] varchar(60) NULL,
    [req type] varchar(50) NULL,
    [ITSSProjectName] varchar(200) NULL,
    [IS_Offshore] varchar(20) NULL,
    [Subtier] varchar(50) NULL,
    [New_Visa_type] varchar(50) NULL,
    [Practice_type] varchar(50) NULL,
    [vertical] varchar(50) NULL,
    [CL_Group] varchar(32) NOT NULL,
    [salesrep] varchar(50) NULL,
    [recruiter] varchar(50) NULL,
    [PO_End] datetime NULL,
    [PO_End_Count] numeric(38,36) NULL,
    [Derived_Rev] real NULL,
    [Derived_GP] real NULL,
    [Backlog_Rev] real NULL,
    [Backlog_GP] real NULL,
    [Expected_Hrs] real NULL,
    [Expected_Total_Hrs] real NULL,
    [ITSS] varchar(100) NOT NULL,
    [client_entity] varchar(50) NULL,
    [newtermdate] datetime NULL,
    [Newoffboardingdate] datetime NULL,
    [HWF_Process_name] varchar(100) NULL,
    [Derived_System_End_date] datetime NULL,
    [Cons_Ageing] int NULL,
    [CP_Name] nvarchar(50) NULL,
    [bill st units] varchar(50) NULL,
    [project city] varchar(50) NULL,
    [project state] varchar(50) NULL,
    [OpportunityID] varchar(50) NULL,
    [OpportunityName] varchar(200) NULL,
    [Bus_days] real NULL,
    [circle] varchar(100) NULL,
    [community_new] varchar(100) NULL,
    [ALT] nvarchar(50) NULL,
    [Market_Leader] varchar(max) NULL,
    [Acct_Owner] nvarchar(50) NULL,
    [st_yymm] int NULL,
    [PortfolioLeader] varchar(max) NULL,
    [ClientPartner] varchar(max) NULL,
    [FP_Proj_ID] varchar(10) NULL,
    [FP_Proj_Name] varchar(max) NULL,
    [FP_TM] varchar(2) NOT NULL,
    [project_type] varchar(500) NULL,
    [FP_Proj_Planned] varchar(10) NULL,
    [Standard Job Title Horizon] nvarchar(2000) NULL,
    [Experience Level Title] varchar(200) NULL,
    [User_Name] varchar(50) NULL,
    [Status] varchar(50) NULL,
    [asstatus] varchar(50) NULL,
    [system_runtime] datetime NOT NULL,
    [BR_Start_date] datetime NULL,
    [Bill_ST] float NULL,
    [Prev_BR] float NULL,
    [ProjType] varchar(2) NOT NULL,
    [Mons_in_Same_Rate] int NULL,
    [Rate_Time_Gr] varchar(20) NULL,
    [Rate_Change_Type] varchar(20) NULL,
    [Net_Addition] numeric(38,36) NULL
);


CREATE TABLE source_layer.SchTask (
    [ID] numeric(18,0) NOT NULL IDENTITY(1,1),
    [SSN] varchar(50) NULL,
    [GCI_ID] varchar(50) NULL,
    [FName] varchar(50) NULL,
    [LName] varchar(50) NULL,
    [Process_ID] numeric(18,0) NOT NULL,
    [Level_ID] int NOT NULL DEFAULT 0,
    [Last_Level] int NOT NULL DEFAULT 0,
    [Initiator] varchar(50) NULL,
    [Initiator_Mail] varchar(50) NULL,
    [Status] varchar(50) NULL,
    [Comments] varchar(8000) NULL,
    [DateCreated] datetime NULL,
    [TrackID] varchar(50) NULL,
    [DateCompleted] datetime NULL,
    [Existing_Resource] varchar(3) NULL,
    [Term_ID] numeric(18,0) NULL,
    [legal_entity] varchar(50) NULL,
    [TS] timestamp NOT NULL,
    CONSTRAINT PK_SchTask PRIMARY KEY (ID)
);

CREATE TABLE source_layer.Hiring_Initiator_Project_Info (
    [ID] numeric(18,0) NOT NULL,
    [Candidate_LName] varchar(50) NULL,
    [Candidate_MI] varchar(50) NULL,
    [Candidate_FName] varchar(50) NULL,
    [Candidate_SSN] varchar(50) NULL,
    [HR_Candidate_JobTitle] varchar(50) NULL,
    [HR_Candidate_JobDescription] varchar(100) NULL,
    [HR_Candidate_DOB] varchar(50) NULL,
    [HR_Candidate_Employee_Type] varchar(50) NULL,
    [HR_Project_Referred_By] varchar(50) NULL,
    [HR_Project_Referral_Fees] varchar(50) NULL,
    [HR_Project_Referral_Units] varchar(50) NULL,
    [HR_Relocation_Request] varchar(50) NULL,
    [HR_Relocation_departure_city] varchar(50) NULL,
    [HR_Relocation_departure_state] varchar(50) NULL,
    [HR_Relocation_departure_airport] varchar(50) NULL,
    [HR_Relocation_departure_date] varchar(50) NULL,
    [HR_Relocation_departure_time] varchar(50) NULL,
    [HR_Relocation_arrival_city] varchar(50) NULL,
    [HR_Relocation_arrival_state] varchar(50) NULL,
    [HR_Relocation_arrival_airport] varchar(50) NULL,
    [HR_Relocation_arrival_date] varchar(50) NULL,
    [HR_Relocation_arrival_time] varchar(50) NULL,
    [HR_Relocation_AccomodationStartDate] varchar(50) NULL,
    [HR_Relocation_AccomodationEndDate] varchar(50) NULL,
    [HR_Relocation_AccomodationStartTime] varchar(50) NULL,
    [HR_Relocation_AccomodationEndTime] varchar(50) NULL,
    [HR_Relocation_CarPickup_Place] varchar(50) NULL,
    [HR_Relocation_CarPickup_AddressLine1] varchar(50) NULL,
    [HR_Relocation_CarPickup_AddressLine2] varchar(50) NULL,
    [HR_Relocation_CarPickup_City] varchar(50) NULL,
    [HR_Relocation_CarPickup_State] varchar(50) NULL,
    [HR_Relocation_CarPickup_Zip] varchar(50) NULL,
    [HR_Relocation_CarReturn_City] varchar(50) NULL,
    [HR_Relocation_CarReturn_State] varchar(50) NULL,
    [HR_Relocation_CarReturn_Place] varchar(50) NULL,
    [HR_Relocation_CarReturn_AddressLine1] varchar(50) NULL,
    [HR_Relocation_CarReturn_AddressLine2] varchar(50) NULL,
    [HR_Relocation_CarReturn_Zip] varchar(50) NULL,
    [HR_Relocation_RentalCarStartDate] varchar(50) NULL,
    [HR_Relocation_RentalCarEndDate] varchar(50) NULL,
    [HR_Relocation_RentalCarStartTime] varchar(50) NULL,
    [HR_Relocation_RentalCarEndTime] varchar(50) NULL,
    [HR_Relocation_MaxClientInvoice] varchar(50) NULL,
    [HR_Relocation_approving_manager] varchar(50) NULL,
    [HR_Relocation_Notes] varchar(5000) NULL,
    [HR_Recruiting_Manager] varchar(50) NULL,
    [HR_Recruiting_AccountExecutive] varchar(50) NULL,
    [HR_Recruiting_Recruiter] varchar(50) NULL,
    [HR_Recruiting_ResourceManager] varchar(50) NULL,
    [HR_Recruiting_Office] varchar(50) NULL,
    [HR_Recruiting_ReqNo] varchar(100) NULL,
    [HR_Recruiting_Direct] varchar(50) NULL,
    [HR_Recruiting_Replacement_For_GCIID] varchar(50) NULL,
    [HR_Recruiting_Replacement_For] varchar(50) NULL,
    [HR_Recruiting_Replacement_Reason] varchar(50) NULL,
    [HR_ClientInfo_ID] varchar(50) NULL,
    [HR_ClientInfo_Name] varchar(60) NULL,
    [HR_ClientInfo_DNB] varchar(50) NULL,
    [HR_ClientInfo_Sector] varchar(50) NULL,
    [HR_ClientInfo_Manager_ID] varchar(50) NULL,
    [HR_ClientInfo_Manager] varchar(50) NULL,
    [HR_ClientInfo_Phone] varchar(50) NULL,
    [HR_ClientInfo_Phone_Extn] varchar(50) NULL,
    [HR_ClientInfo_Email] varchar(50) NULL,
    [HR_ClientInfo_Fax] varchar(50) NULL,
    [HR_ClientInfo_Cell] varchar(50) NULL,
    [HR_ClientInfo_Pager] varchar(50) NULL,
    [HR_ClientInfo_Pager_Pin] varchar(50) NULL,
    [HR_ClientAgreements_SendTo] varchar(50) NULL,
    [HR_ClientAgreements_Phone] varchar(50) NULL,
    [HR_ClientAgreements_Phone_Extn] varchar(50) NULL,
    [HR_ClientAgreements_Email] varchar(50) NULL,
    [HR_ClientAgreements_Fax] varchar(50) NULL,
    [HR_ClientAgreements_Cell] varchar(50) NULL,
    [HR_ClientAgreements_Pager] varchar(50) NULL,
    [HR_ClientAgreements_Pager_Pin] varchar(50) NULL,
    [HR_Project_SendInvoicesTo] varchar(100) NULL,
    [HR_Project_AddressToSend1] varchar(150) NULL,
    [HR_Project_AddressToSend2] varchar(150) NULL,
    [HR_Project_City] varchar(50) NULL,
    [HR_Project_State] varchar(50) NULL,
    [HR_Project_Zip] varchar(50) NULL,
    [HR_Project_Phone] varchar(50) NULL,
    [HR_Project_Phone_Extn] varchar(50) NULL,
    [HR_Project_Email] varchar(50) NULL,
    [HR_Project_Fax] varchar(50) NULL,
    [HR_Project_Cell] varchar(50) NULL,
    [HR_Project_Pager] varchar(50) NULL,
    [HR_Project_Pager_Pin] varchar(50) NULL,
    [HR_Project_ST] varchar(50) NULL,
    [HR_Project_OT] varchar(50) NULL,
    [HR_Project_ST_Off] varchar(50) NULL,
    [HR_Project_OT_Off] varchar(50) NULL,
    [HR_Project_ST_Units] varchar(50) NULL,
    [HR_Project_OT_Units] varchar(50) NULL,
    [HR_Project_ST_Off_Units] varchar(50) NULL,
    [HR_Project_OT_Off_Units] varchar(50) NULL,
    [HR_Project_StartDate] varchar(50) NULL,
    [HR_Project_EndDate] varchar(50) NULL,
    [HR_Project_Location_AddressLine1] varchar(50) NULL,
    [HR_Project_Location_AddressLine2] varchar(50) NULL,
    [HR_Project_Location_City] varchar(50) NULL,
    [HR_Project_Location_State] varchar(50) NULL,
    [HR_Project_Location_Zip] varchar(50) NULL,
    [HR_Project_InvoicingTerms] varchar(50) NULL,
    [HR_Project_PaymentTerms] varchar(50) NULL,
    [HR_Project_EndClient_ID] varchar(50) NULL,
    [HR_Project_EndClient_Name] varchar(60) NULL,
    [HR_Project_EndClient_Sector] varchar(50) NULL,
    [HR_Accounts_Person] varchar(50) NULL,
    [HR_Accounts_PhoneNo] varchar(50) NULL,
    [HR_Accounts_PhoneNo_Extn] varchar(50) NULL,
    [HR_Accounts_Email] varchar(50) NULL,
    [HR_Accounts_FaxNo] varchar(50) NULL,
    [HR_Accounts_Cell] varchar(50) NULL,
    [HR_Accounts_Pager] varchar(50) NULL,
    [HR_Accounts_Pager_Pin] varchar(50) NULL,
    [HR_Project_Referrer_ID] varchar(50) NULL,
    [UserCreated] varchar(50) NULL,
    [DateCreated] varchar(50) NULL,
    [HR_Week_Cycle] int NULL,
    [Project_Name] varchar(255) NULL,
    [transition] varchar(50) NULL,
    [Is_OT_Allowed] varchar(50) NULL,
    [HR_Business_Type] varchar(50) NULL,
    [WebXl_EndClient_ID] varchar(50) NULL,
    [WebXl_EndClient_Name] varchar(60) NULL,
    [Client_Offer_Acceptance_Date] varchar(50) NULL,
    [Project_Type] varchar(50) NULL,
    [req_division] varchar(200) NULL,
    [Client_Compliance_Checks_Reqd] varchar(50) NULL,
    [HSU] varchar(50) NULL,
    [HSUDM] varchar(50) NULL,
    [Payroll_Location] varchar(50) NULL,
    [Is_DT_Allowed] varchar(50) NULL,
    [SBU] varchar(2) NULL,
    [BU] varchar(50) NULL,
    [Dept] varchar(2) NULL,
    [HCU] varchar(50) NULL,
    [Project_Category] varchar(50) NULL,
    [Delivery_Model] varchar(50) NULL,
    [BPOS_Project] varchar(3) NULL,
    [ER_Person] varchar(50) NULL,
    [Print_Invoice_Address1] varchar(100) NULL,
    [Print_Invoice_Address2] varchar(100) NULL,
    [Print_Invoice_City] varchar(50) NULL,
    [Print_Invoice_State] varchar(50) NULL,
    [Print_Invoice_Zip] varchar(50) NULL,
    [Mail_Invoice_Address1] varchar(100) NULL,
    [Mail_Invoice_Address2] varchar(100) NULL,
    [Mail_Invoice_City] varchar(50) NULL,
    [Mail_Invoice_State] varchar(50) NULL,
    [Mail_Invoice_Zip] varchar(50) NULL,
    [Project_Zone] varchar(50) NULL,
    [Emp_Identifier] varchar(50) NULL,
    [CRE_Person] varchar(50) NULL,
    [HR_Project_Location_Country] varchar(50) NULL,
    [Agency] varchar(50) NULL,
    [pwd] varchar(50) NULL,
    [PES_Doc_Sent] varchar(50) NULL,
    [PES_Confirm_Doc_Rcpt] varchar(50) NULL,
    [PES_Clearance_Rcvd] varchar(50) NULL,
    [PES_Doc_Sent_Date] varchar(50) NULL,
    [PES_Confirm_Doc_Rcpt_Date] varchar(50) NULL,
    [PES_Clearance_Rcvd_Date] varchar(50) NULL,
    [Inv_Pay_Terms_Notes] text NULL,
    [CBC_Notes] text NULL,
    [Benefits_Plan] varchar(50) NULL,
    [BillingCompany] varchar(50) NULL,
    [SPINOFF_CPNY] varchar(50) NULL,
    [Position_Type] varchar(50) NULL,
    [I9_Approver] varchar(50) NULL,
    [FP_BILL_Rate] varchar(50) NULL,
    [TSLead] varchar(50) NULL,
    [Inside_Sales] varchar(50) NULL,
    [Markup] varchar(50) NULL,
    [Maximum_Allowed_Markup] varchar(50) NULL,
    [Actual_Markup] varchar(50) NULL,
    [SCA_Hourly_Bill_Rate] varchar(50) NULL,
    [HR_Project_StartDate_Change_Reason] varchar(100) NULL,
    [source] varchar(50) NULL,
    [HR_Recruiting_VMO] varchar(50) NULL,
    [HR_Recruiting_Inside_Sales] varchar(50) NULL,
    [HR_Recruiting_TL] varchar(50) NULL,
    [HR_Recruiting_NAM] varchar(50) NULL,
    [HR_Recruiting_ARM] varchar(50) NULL,
    [HR_Recruiting_RM] varchar(50) NULL,
    [HR_Recruiting_ReqID] varchar(50) NULL,
    [HR_Recruiting_TAG] varchar(50) NULL,
    [DateUpdated] varchar(50) NULL,
    [UserUpdated] varchar(50) NULL,
    [Is_Swing_Shift_Associated_With_It] varchar(50) NULL,
    [FP_Bill_Rate_OT] varchar(50) NULL,
    [Not_To_Exceed_YESNO] varchar(10) NULL,
    [Exceed_YESNO] varchar(10) NULL,
    [Is_OT_Billable] varchar(5) NULL,
    [Is_premium_project_Associated_With_It] varchar(50) NULL,
    [ITSS_Business_Development_Manager] varchar(50) NULL,
    [Practice_type] varchar(50) NULL,
    [Project_billing_type] varchar(50) NULL,
    [Resource_billing_type] varchar(50) NULL,
    [Type_Consultant_category] varchar(50) NULL,
    [Unique_identification_ID_Doc] varchar(100) NULL,
    [Region1] varchar(100) NULL,
    [Region2] varchar(100) NULL,
    [Region1_percentage] varchar(10) NULL,
    [Region2_percentage] varchar(10) NULL,
    [Soc_Code] varchar(300) NULL,
    [Soc_Desc] varchar(300) NULL,
    [req_duration] int NULL,
    [Non_Billing_Type] varchar(50) NULL,
    [Worker_Entity_ID] varchar(30) NULL,
    [OraclePersonID] varchar(30) NULL,
    [Collabera_Email_ID] varchar(100) NULL,
    [Onsite_Consultant_Relationship_Manager] varchar(50) NULL,
    [HR_project_county] varchar(100) NULL,
    [EE_WF_Reasons] varchar(50) NULL,
    [GradeName] varchar(50) NULL,
    [ROLEFAMILY] varchar(50) NULL,
    [SUBDEPARTMENT] varchar(100) NULL,
    [MSProjectType] varchar(50) NULL,
    [NetsuiteProjectId] varchar(50) NULL,
    [NetsuiteCreatedDate] varchar(50) NULL,
    [NetsuiteModifiedDate] varchar(50) NULL,
    [StandardJobTitle] varchar(100) NULL,
    [community] varchar(100) NULL,
    [parent_Account_name] varchar(100) NULL,
    [Timesheet_Manager] varchar(255) NULL,
    [TimeSheetManagerType] varchar(255) NULL,
    [Timesheet_Manager_Phone] varchar(255) NULL,
    [Timesheet_Manager_Email] varchar(255) NULL,
    [HR_Project_Major_Group] varchar(255) NULL,
    [HR_Project_Minor_Group] varchar(255) NULL,
    [HR_Project_Broad_Group] varchar(255) NULL,
    [HR_Project_Detail_Group] varchar(255) NULL,
    [9Hours_Allowed] varchar(3) NULL,
    [9Hours_Effective_Date] varchar(50) NULL,
    CONSTRAINT IX_Hiring_Initiator_Project_Info UNIQUE (ID)
);


CREATE TABLE source_layer.Timesheet_New (
    gci_id INT NOT NULL,
    pe_date DATETIME NOT NULL,
    task_id NUMERIC(18,9) NOT NULL,
    c_date DATETIME NULL,
    ST FLOAT NULL,
    OT FLOAT NULL,
    TIME_OFF FLOAT NULL,
    HO FLOAT NULL,
    DT FLOAT NULL,
    NON_ST FLOAT NULL,
    NON_OT FLOAT NULL,
    Sick_Time FLOAT NULL,
    NON_Sick_Time FLOAT NULL,
    NON_DT FLOAT NULL
);



CREATE TABLE source_layer.report_392_all (
    id NUMERIC(18,9) NULL,
    [gci id] VARCHAR(50) NULL,
    [first name] VARCHAR(50) NULL,
    [last name] VARCHAR(50) NULL,
    [employee type] VARCHAR(8000) NULL,
    [recruiting manager] VARCHAR(50) NULL,
    [resource manager] VARCHAR(50) NULL,
    [salesrep] VARCHAR(50) NULL,
    [inside_sales] VARCHAR(50) NULL,
    [recruiter] VARCHAR(50) NULL,
    [req type] VARCHAR(50) NULL,
    [ms_type] VARCHAR(28) NULL,
    [client code] VARCHAR(50) NULL,
    [client name] VARCHAR(60) NULL,
    [client_type] VARCHAR(50) NULL,
    [job title] VARCHAR(50) NULL,
    [bill st] VARCHAR(50) NULL,
    [visa type] VARCHAR(50) NULL,
    [bill st units] VARCHAR(50) NULL,
    salary MONEY NULL,
    [salary units] VARCHAR(50) NULL,
    [pay st] FLOAT NULL,
    [pay st units] VARCHAR(50) NULL,
    [start date] DATETIME NULL,
    [end date] DATETIME NULL,
    [po start date] VARCHAR(50) NULL,
    [po end date] VARCHAR(50) NULL,
    [project city] VARCHAR(50) NULL,
    [project state] VARCHAR(50) NULL,
    [no of free hours] VARCHAR(50) NULL,
    [hr_business_type] VARCHAR(50) NULL,
    [ee_wf_reason] VARCHAR(50) NULL,
    [singleman company] VARCHAR(50) NULL,
    status VARCHAR(50) NULL,
    termination_reason VARCHAR(100) NULL,
    [wf created on] DATETIME NULL,
    hcu VARCHAR(50) NULL,
    hsu VARCHAR(50) NULL,
    [project zip] VARCHAR(50) NULL,
    cre_person VARCHAR(50) NULL,
    assigned_hsu VARCHAR(10) NULL,
    req_category VARCHAR(50) NULL,
    gpm MONEY NULL,
    gp MONEY NULL,
    aca_cost REAL NULL,
    aca_classification VARCHAR(50) NULL,
    markup VARCHAR(3) NOT NULL,
    actual_markup VARCHAR(50) NULL,
    maximum_allowed_markup VARCHAR(50) NULL,
    submitted_bill_rate MONEY NULL,
    req_division VARCHAR(200) NULL,
    [pay rate to consultant] VARCHAR(50) NULL,
    location VARCHAR(50) NULL,
    rec_region VARCHAR(50) NULL,
    client_region VARCHAR(50) NULL,
    dm VARCHAR(50) NULL,
    delivery_director VARCHAR(50) NULL,
    bu VARCHAR(50) NULL,
    es VARCHAR(50) NULL,
    nam VARCHAR(50) NULL,
    client_sector VARCHAR(50) NULL,
    skills VARCHAR(2500) NULL,
    pskills VARCHAR(4000) NULL,
    business_manager NVARCHAR(MAX) NULL,
    vmo VARCHAR(50) NULL,
    rec_name VARCHAR(500) NULL,
    Req_ID NUMERIC(18,9) NULL,
    received DATETIME NULL,
    Submitted DATETIME NULL,
    responsetime VARCHAR(53) NULL,
    Inhouse VARCHAR(3) NOT NULL,
    Net_Bill_Rate MONEY NULL,
    Loaded_Pay_Rate MONEY NULL,
    NSO VARCHAR(100) NULL,
    ESG_Vertical VARCHAR(100) NULL,
    ESG_Industry VARCHAR(100) NULL,
    ESG_DNA VARCHAR(100) NULL,
    ESG_NAM1 VARCHAR(100) NULL,
    ESG_NAM2 VARCHAR(100) NULL,
    ESG_NAM3 VARCHAR(100) NULL,
    ESG_SAM VARCHAR(100) NULL,
    ESG_ES VARCHAR(100) NULL,
    ESG_BU VARCHAR(100) NULL,
    SUB_GPM MONEY NULL,
    manager_id NUMERIC(18,9) NULL,
    Submitted_By VARCHAR(50) NULL,
    HWF_Process_name VARCHAR(100) NULL,
    Transition VARCHAR(100) NULL,
    ITSS VARCHAR(100) NOT NULL,
    GP2020 MONEY NULL,
    GPM2020 MONEY NULL,
    isbulk BIT NOT NULL,
    jump BIT NOT NULL,
    client_class VARCHAR(20) NULL,
    MSP VARCHAR(50) NULL,
    DTCUChoice1 VARCHAR(60) NULL,
    SubCat VARCHAR(60) NULL,
    IsClassInitiative BIT NULL,
    division VARCHAR(50) NULL,
    divstart_date DATETIME NULL,
    divend_date DATETIME NULL,
    tl VARCHAR(50) NULL,
    resource_manager VARCHAR(50) NULL,
    recruiting_manager VARCHAR(50) NULL,
    VAS_Type VARCHAR(100) NULL,
    BUCKET VARCHAR(50) NULL,
    RTR_DM VARCHAR(50) NULL,
    ITSSProjectName VARCHAR(200) NULL,
    RegionGroup VARCHAR(50) NULL,
    client_Markup VARCHAR(20) NULL,
    Subtier VARCHAR(50) NULL,
    Subtier_Address1 VARCHAR(50) NULL,
    Subtier_Address2 VARCHAR(50) NULL,
    Subtier_City VARCHAR(50) NULL,
    Subtier_State VARCHAR(50) NULL,
    Hiresource VARCHAR(100) NULL,
    is_Hotbook_Hire INT NULL,
    Client_RM VARCHAR(50) NULL,
    Job_Description VARCHAR(100) NULL,
    Client_Manager VARCHAR(50) NULL,
    end_date_at_client DATETIME NULL,
    term_date DATETIME NULL,
    employee_status VARCHAR(50) NULL,
    Level_ID INT NULL,
    OpsGrp VARCHAR(50) NULL,
    Level_Name VARCHAR(50) NULL,
    Min_levelDatetime DATETIME NULL,
    Max_levelDatetime DATETIME NULL,
    First_Interview_date DATETIME NULL,
    [Is REC CES?] VARCHAR(5) NULL,
    [Is CES Initiative?] VARCHAR(5) NULL,
    VMO_Access VARCHAR(50) NULL,
    Billing_Type VARCHAR(50) NULL,
    VASSOW VARCHAR(3) NOT NULL,
    Worker_Entity_ID VARCHAR(30) NULL,
    Circle VARCHAR(50) NULL,
    VMO_Access1 VARCHAR(50) NULL,
    VMO_Access2 VARCHAR(50) NULL,
    VMO_Access3 VARCHAR(50) NULL,
    VMO_Access4 VARCHAR(50) NULL,
    Inside_Sales_Person VARCHAR(50) NULL,
    admin_1701 VARCHAR(50) NULL,
    corrected_staffadmin_1701 VARCHAR(50) NULL,
    HR_Billing_Placement_Net_Fee MONEY NULL,
    New_Visa_type VARCHAR(50) NULL,
    newenddate DATETIME NULL,
    Newoffboardingdate DATETIME NULL,
    NewTermdate DATETIME NULL,
    newhrisenddate DATETIME NULL,
    rtr_location VARCHAR(50) NULL,
    HR_Recruiting_TL VARCHAR(100) NULL,
    client_entity VARCHAR(50) NULL,
    client_consent BIT NULL,
    Ascendion_MetalReqID NUMERIC(18,9) NULL,
    eeo VARCHAR(200) NULL,
    veteran VARCHAR(150) NULL,
    Gender VARCHAR(50) NULL,
    Er_person VARCHAR(50) NULL,
    wfmetaljobdescription NVARCHAR(MAX) NULL,
    HR_Candidate_Salary MONEY NULL,
    Interview_CreatedDate DATETIME NULL,
    Interview_on_Date DATETIME NULL,
    IS_SOW VARCHAR(7) NULL,
    IS_Offshore VARCHAR(20) NULL,
    New_VAS VARCHAR(4) NULL,
    VerticalName NVARCHAR(510) NULL,
    Client_Group1 VARCHAR(19) NOT NULL,
    Billig_Type VARCHAR(8) NOT NULL,
    [Super Merged Name] VARCHAR(200) NULL,
    New_Category VARCHAR(11) NULL,
    New_business_type VARCHAR(100) NULL,
    OpportunityID VARCHAR(50) NULL,
    OpportunityName VARCHAR(200) NULL,
    Ms_ProjectId INT NULL,
    MS_ProjectName VARCHAR(200) NULL,
    ORC_ID VARCHAR(30) NULL,
    Market_Leader NVARCHAR(MAX) NULL,
    Circle_Metal VARCHAR(100) NULL,
    Community_New_Metal VARCHAR(100) NULL,
    Employee_Category VARCHAR(50) NULL,
    IsBillRateSkip BIT NULL,
    BillRate DECIMAL(18,9) NULL,
    RoleFamily VARCHAR(300) NULL,
    SubRoleFamily VARCHAR(300) NULL,
    [Standard JobTitle] VARCHAR(500) NULL,
    ClientInterviewRequired INT NULL,
    Redeploymenthire INT NULL,
    HRBrandLevelId INT NULL,
    HRBandTitle VARCHAR(300) NULL,
    latest_termination_reason VARCHAR(200) NULL,
    latest_termination_date DATETIME NULL,
    Community VARCHAR(100) NULL,
    ReqFulfillmentReason VARCHAR(200) NULL,
    EngagementType VARCHAR(500) NULL,
    RedepLedBy VARCHAR(200) NULL,
    Can_ExperienceLevelTitle VARCHAR(200) NULL,
    Can_StandardJobTitleHorizon NVARCHAR(4000) NULL,
    CandidateEmail VARCHAR(100) NULL,
    Offboarding_Reason VARCHAR(100) NULL,
    Offboarding_Initiated DATETIME NULL,
    Offboarding_Status VARCHAR(100) NULL,
    replcament_GCIID INT NULL,
    replcament_EmployeeName VARCHAR(500) NULL,
    [Senior Manager] VARCHAR(50) NULL,
    [Associate Manager] VARCHAR(50) NULL,
    [Director - Talent Engine] VARCHAR(50) NULL,
    Manager VARCHAR(50) NULL,
    Rec_ExperienceLevelTitle VARCHAR(200) NULL,
    Rec_StandardJobTitleHorizon NVARCHAR(4000) NULL,
    Task_Id INT NULL,
    proj_ID VARCHAR(50) NULL,
    Projdesc CHAR(60) NULL,
    Client_Group VARCHAR(19) NOT NULL,
    billST_New FLOAT NULL,
    [Candidate city] VARCHAR(50) NULL,
    [Candidate State] VARCHAR(50) NULL,
    C2C_W2_FTE VARCHAR(13) NOT NULL,
    FP_TM VARCHAR(2) NOT NULL
);

CREATE TABLE source_layer.vw_billing_timesheet_daywise_ne (
    [ID] numeric(18,9) NULL,
    [GCI_ID] int NOT NULL,
    [PE_DATE] datetime NOT NULL,
    [WEEK_DATE] datetime NULL,
    [BILLABLE] varchar(3) NOT NULL,
    [Approved_hours(ST)] float NULL,
    [Approved_hours(Non_ST)] float NULL,
    [Approved_hours(OT)] float NULL,
    [Approved_hours(Non_OT)] float NULL,
    [Approved_hours(DT)] float NULL,
    [Approved_hours(Non_DT)] float NULL,
    [Approved_hours(Sick_Time)] float NULL,
    [Approved_hours(Non_Sick_Time)] float NULL
);


CREATE TABLE source_layer.vw_consultant_timesheet_daywise (
    [ID] numeric(18,9) NOT NULL,
    [GCI_ID] int NOT NULL,
    [PE_DATE] datetime NOT NULL,
    [WEEK_DATE] datetime NULL,
    [BILLABLE] varchar(3) NOT NULL,
    [Consultant_hours(ST)] float NULL,
    [Consultant_hours(OT)] float NULL,
    [Consultant_hours(DT)] float NULL
);


CREATE TABLE [source_layer].[DimDate](
	[DateKey] [int] NOT NULL,
	[Date] [datetime] NULL,
	[DayOfMonth] [varchar](2) NULL,
	[DayName] [varchar](9) NULL,
	[WeekOfYear] [varchar](2) NULL,
	[Month] [varchar](2) NULL,
	[MonthName] [varchar](9) NULL,
	[MonthOfQuarter] [varchar](2) NULL,
	[Quarter] [char](1) NULL,
	[QuarterName] [varchar](9) NULL,
	[Year] [char](4) NULL,
	[YearName] [char](7) NULL,
	[MonthYear] [char](10) NULL,
	[MMYYYY] [char](6) NULL,
	[DaysInMonth] [int] NULL,
	[MM-YYYY] [varchar](10) NULL,
	[YYYYMM] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[DateKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]




CREATE TABLE [source_layer].[holidays_Mexico](
	[Holiday_Date] [datetime] NOT NULL,
	[Description] [varchar](50) NOT NULL,
	[Location] [varchar](10) NULL,
	[Source_type] [varchar](50) NOT NULL
) ON [PRIMARY]


CREATE TABLE [source_layer].[holidays_Canada](
	[Holiday_Date] [datetime] NOT NULL,
	[Description] [varchar](100) NULL,
	[Location] [varchar](10) NULL,
	[Source_type] [varchar](50) NOT NULL
) ON [PRIMARY]


CREATE TABLE [source_layer].[holidays](
	[Holiday_Date] [datetime] NOT NULL,
	[Description] [varchar](50) NOT NULL,
	[Location] [varchar](10) NULL,
	[Source_type] [varchar](50) NOT NULL
) ON [PRIMARY]


CREATE TABLE [source_layer].[holidays_India](
	[Holiday_Date] [datetime] NOT NULL,
	[Description] [varchar](50) NOT NULL,
	[Location] [varchar](10) NULL,
	[Source_type] [varchar](50) NOT NULL
) ON [PRIMARY]
